services:
  app:
    build:
      context: .
    container_name: app_container
    platform: linux/amd64
    ports:
      - "7099:7099"
    volumes:
      - .:/app
    entrypoint: ["bash", "-c", "ls -l /app/zoom-sdk && cd /app/build && exec ./zoomsdk && uvicorn notetakers.app:app --host 0.0.0.0 --port 7099 --reload"]
    environment:
      - DEBIAN_FRONTEND=noninteractive
    networks:
      - app_network

networks:
  app_network:
    driver: bridge