version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app_container
    platform: linux/amd64
    ports:
      - "7099:7099"
    volumes:
      - .:/app
    entrypoint: ["bash", "-c", "pulseaudio --start && uvicorn notetakers.app:app --host 0.0.0.0 --port 7099 --reload"]
    environment:
      - DEBIAN_FRONTEND=noninteractive

  zoomsdk:
    build:
      context: ./zoom-sdk
    container_name: zoomsdk_container
    platform: linux/amd64
    volumes:
      - ./zoom-sdk:/tmp/meeting-sdk-linux-sample
    ports:
      - "3101:3101"
    entrypoint: ["/tini", "--", "./bin/entry.sh"]
    environment:
      - DEBIAN_FRONTEND=noninteractive