services:
  app:
    build:
      context: .
    container_name: app_container
    platform: linux/amd64
    ports:
      - "7099:7099"
    entrypoint: ["bash", "-c", "cd /app && ./start.sh"]
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ./notetakers:/app/notetakers
    networks:
      - app_network

networks:
  app_network:
    driver: bridge