services:
  app:
    build:
      context: .
    container_name: app_container
    platform: linux/amd64
    ports:
      - "7099:7099"
    entrypoint: ["bash", "-c", "ls -l /app && cd /app && uvicorn notetakers.app:app --host 0.0.0.0 --port 7099 --reload --reload-dir /app"]
    environment:
      - DEBIAN_FRONTEND=noninteractive
    networks:
      - app_network

networks:
  app_network:
    driver: bridge