import type { Metadata } from "next";
import "@/app/globals.css";
import { SidebarContextProvider } from "@/components/sidebar-context";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { NextUIProvider } from "@nextui-org/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <NextUIProvider>
      <SidebarContextProvider>
        <SidebarProvider>
          <div style={{ display: "flex" }}>
            <AppSidebar />
            <main style={{ flex: 1 }}>
              {children}
            </main>
          </div>
        </SidebarProvider>
      </SidebarContextProvider>
    </NextUIProvider>
  );
}