#### !! Do not store plain text credentials in production environments !!
#### File Format: https://cliutils.github.io/CLI11/book/chapters/config.html#configure-file-format

# Zoom Meeting SDK Client ID
client-id="bIwyq7_7TempWjqkOXEwA"

# Zoom Meeting SDK Client Secret
client-secret="9x9heO1phgqUaPmtHg6B3NvZp4Ejuhl4"

# Use a join-url or a meeting-id and password
join-url="https://us05web.zoom.us/j/86573055750?pwd=6JNwPuvmYFuDprLQQjvTswdavK1Zto.1"

[RawAudio]
file="meeting-audio.pcm"